/**
 *  JSoko - A Java implementation of the game of Sokoban
 *  Copyright (c) 2012 by Matthias Meger, Germany
 *
 *  This file is part of JSoko.
 *
 *	JSoko is free software; you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation; either version 2 of the License, or
 *	(at your option) any later version.
 *
 *	This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.sokoban_online.jsoko.gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

import de.sokoban_online.jsoko.resourceHandling.Settings;
import de.sokoban_online.jsoko.resourceHandling.Texts;
import de.sokoban_online.jsoko.translator.Translator;
import de.sokoban_online.jsoko.utilities.Utilities;


/**
 *
 * @author Bill
 */
public class SettingsFrame extends javax.swing.JFrame {

    private String[] fontList;
    private final String[] fontSizes = {"8", "10", "11", "12", "14", "16", "18",
        "20", "24", "30", "36", "40", "48", "60", "72"};
    protected static final int DEFAULT_SIZE = 4;
    private String resultName;
    private boolean isBold;
    private boolean isItalic;

    /** Creates new form SettingsFrame */
    public SettingsFrame() {
        initComponents();
    }

    SettingsFrame(GUI applicationGUI) {
        this.applicationGUI = applicationGUI;
        initComponents();
        this.setTitle("JSoko - settings");
        //when apply buttons are pressed choose the first option of their corresponding comboboxes
        languageName = (String) comboBoxLanguages.getItemAt(0);
        lookAndFeelName = (String) jComboBoxLookAndFeelSelection.getItemAt(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxLanguages = new javax.swing.JComboBox();
        jButtonTranslate = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jCheckBoxReverseMoves = new javax.swing.JCheckBox(Texts.getText("treat_reverse_moves_as_undo"), Settings.treatReverseMovesAsUndo);
        jCheckBoxSinglestepundo = new javax.swing.JCheckBox(Texts.getText("singlestepundo"), Settings.singleStepUndoRedo);
        jCheckBoxOptimize_moves = new javax.swing.JCheckBox(Texts.getText("optimize_moves"), Settings.optimizeMovesBetweenPushes);
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxDetectSimpleDeadlocks = new javax.swing.JCheckBox(Texts.getText("detectSimpleDeadlocks"), Settings.detectSimpleDeadlocks);
        jCheckBoxDetectFreezeDeadlocks = new javax.swing.JCheckBox(Texts.getText("detectFreezeDeadlocks"),Settings.detectFreezeDeadlocks);
        jCheckBoxDetectCorralDeadlocks = new javax.swing.JCheckBox(Texts.getText("detectCorralDeadlocks"),Settings.detectCorralDeadlocks);
        jCheckBoxDetectBipartiteDeadlocks = new javax.swing.JCheckBox(Texts.getText("detectBipartiteDeadlocks"),Settings.detectBipartiteDeadlocks);
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPush = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMove = new javax.swing.JTextField();
        jTextFieldPushToGoal = new javax.swing.JTextField();
        jButtonBrowsePush = new javax.swing.JButton();
        jButtonBrowseMove = new javax.swing.JButton();
        jButtonBrowsePushToGoal = new javax.swing.JButton();
        jButtonPlayPush = new javax.swing.JButton();
        jButtonPlayPushToGoal = new javax.swing.JButton();
        jButtonPlayMove = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBoxSound = new javax.swing.JCheckBox(Texts.getText("sound"), Settings.soundEffectsEnabled);
        jSlider1 = new javax.swing.JSlider(0,100,75);
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jComboBoxLookAndFeelSelection = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonApplyLookAndFeel = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        panelColorDisplayMovesPushes = new javax.swing.JPanel();
        jButtonColorDisplayMovesPushes = new javax.swing.JButton();
        jLabelColorDisplayMovesPushes = new javax.swing.JLabel();
        jLabelColorBackgroundMovesPushes = new javax.swing.JLabel();
        panelColorBackgroundMovesPushes = new javax.swing.JPanel();
        jButtonColorBackgroundMovesPushes = new javax.swing.JButton();
        jLabelColorInfobar = new javax.swing.JLabel();
        panelColorInfobar = new javax.swing.JPanel();
        jButtonColorInfobar = new javax.swing.JButton();
        jLabelColorInfobarFrame = new javax.swing.JLabel();
        panelColorInfobarFrame = new javax.swing.JPanel();
        jButtonColorInfobarFrame = new javax.swing.JButton();
        jLabelColorInfobarText = new javax.swing.JLabel();
        panelColorInfobarText = new javax.swing.JPanel();
        jButtonColorInfobarText = new javax.swing.JButton();
        jLabelColorSelectedObjectFrame = new javax.swing.JLabel();
        panelColorSelectedObjectFrame = new javax.swing.JPanel();
        jButtonColorSelectedObjectFrame = new javax.swing.JButton();
        jLabelColorNumberOfBoxesGoals = new javax.swing.JLabel();
        panelColorNumberOfBoxesGoals = new javax.swing.JPanel();
        jButtonColorNumberOfBoxesGoals = new javax.swing.JButton();
        jLabelColorSelectedBoxFrame = new javax.swing.JLabel();
        panelColorSelectedBoxFrame = new javax.swing.JPanel();
        jButtonColorSelectedBoxFrame = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButtonNimRODLF = new javax.swing.JButton();
        jButtonLoadThemeNimRODLF = new javax.swing.JButton();
        jButtonCustomizeNimRODLF = new javax.swing.JButton();
        jButtonSetDefaultThemeNimRODLF = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        bold = new javax.swing.JCheckBox();
        italic = new javax.swing.JCheckBox();
        fontNameChoice = new java.awt.List(8);
        fontSizeChoice = new java.awt.List(8);
        resultFont = new javax.swing.JLabel("Text Example",JLabel.CENTER);
        okButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("About Language"));

        jLabel1.setText(Texts.getText("language"));

        UpdateSettingsFrame();
        comboBoxLanguages.addActionListener(evt -> comboBoxLanguagesActionPerformed(evt));

        jButtonTranslate.setText(Texts.getText("translate"));
        jButtonTranslate.setActionCommand("translate");
        jButtonTranslate.addActionListener(applicationGUI);

        jButton1.setText("Apply");
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonTranslate, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButtonTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Playgame"));

        jCheckBoxReverseMoves.setText(Texts.getText("treat_reverse_moves_as_undo"));

        jCheckBoxSinglestepundo.setText(Texts.getText("singlestepundo"));

        jCheckBoxOptimize_moves.setText(Texts.getText("optimize_moves"));

        jCheckBox9.setText("show reachable player squares (Does not work)");

        jCheckBox10.setText("show reachable box squares  (Does not work)");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxOptimize_moves)
                    .addComponent(jCheckBoxSinglestepundo)
                    .addComponent(jCheckBoxReverseMoves)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox9))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxSinglestepundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxReverseMoves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxOptimize_moves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox10)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jCheckBoxReverseMoves.setActionCommand("reverseMoves");
        jCheckBoxReverseMoves.addActionListener(applicationGUI);
        jCheckBoxSinglestepundo.setActionCommand("singleStepUndo");
        jCheckBoxSinglestepundo.addActionListener(applicationGUI);
        jCheckBoxOptimize_moves.setActionCommand("optimizeBetweenMoves");
        jCheckBoxOptimize_moves.addActionListener(applicationGUI);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(Texts.getText("deadlocks")));

        jCheckBoxDetectSimpleDeadlocks.setText(Texts.getText("detectSimpleDeadlocks"));
        jCheckBoxDetectSimpleDeadlocks.setActionCommand("detectSimpleDeadlocks");
        jCheckBoxDetectSimpleDeadlocks.addActionListener(applicationGUI);

        jCheckBoxDetectFreezeDeadlocks.setText(Texts.getText("detectFreezeDeadlocks"));
        jCheckBoxDetectFreezeDeadlocks.setActionCommand("detectFreezeDeadlocks");
        jCheckBoxDetectFreezeDeadlocks.addActionListener(applicationGUI);

        jCheckBoxDetectCorralDeadlocks.setText(Texts.getText("detectCorralDeadlocks"));
        jCheckBoxDetectCorralDeadlocks.setActionCommand("detectCorralDeadlocks");
        jCheckBoxDetectCorralDeadlocks.addActionListener(applicationGUI);

        jCheckBoxDetectBipartiteDeadlocks.setText(Texts.getText("detectBipartiteDeadlocks"));
        jCheckBoxDetectBipartiteDeadlocks.setActionCommand("detectBipartiteDeadlocks");
        jCheckBoxDetectBipartiteDeadlocks.addActionListener(applicationGUI);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxDetectSimpleDeadlocks)
                    .addComponent(jCheckBoxDetectFreezeDeadlocks)
                    .addComponent(jCheckBoxDetectCorralDeadlocks)
                    .addComponent(jCheckBoxDetectBipartiteDeadlocks))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxDetectSimpleDeadlocks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDetectFreezeDeadlocks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDetectCorralDeadlocks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDetectBipartiteDeadlocks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(616, 616, 616))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel6, jPanel8});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("General", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sounds"));

        jLabel2.setText("Push");

        jTextFieldPush.setText(Settings.get("PushSoundFile"));

        jLabel3.setText("Move");

        jLabel4.setText("PushToGoal");

        jTextFieldMove.setText(Settings.get("MoveSoundFile"));

        jTextFieldPushToGoal.setText(Settings.get("PushToGoalSoundFile"));

        jButtonBrowsePush.setText("Browse");
        jButtonBrowsePush.addActionListener(evt -> jButtonBrowsePushActionPerformed(evt));

        jButtonBrowseMove.setText("Browse");
        jButtonBrowseMove.addActionListener(evt -> jButtonBrowseMoveActionPerformed(evt));

        jButtonBrowsePushToGoal.setText("Browse");
        jButtonBrowsePushToGoal.addActionListener(evt -> jButtonBrowsePushToGoalActionPerformed(evt));

        jButtonPlayPush.setText("Play");
        jButtonPlayPush.setIcon(Utilities.getIcon("1rightarrow (oxygen).png", ""));
        jButtonPlayPush.setHorizontalTextPosition(SwingConstants.RIGHT);
        jButtonPlayPush.addActionListener(evt -> jButtonPlayPushActionPerformed(evt));

        jButtonPlayPushToGoal.setText("Play");
        jButtonPlayPushToGoal.setIcon(Utilities.getIcon("1rightarrow (oxygen).png", ""));
        jButtonPlayPushToGoal.setHorizontalTextPosition(SwingConstants.RIGHT);

        jButtonPlayMove.setText("Play");
        jButtonPlayMove.setIcon(Utilities.getIcon("1rightarrow (oxygen).png", ""));
        jButtonPlayMove.setHorizontalTextPosition(SwingConstants.RIGHT);
        jButtonPlayMove.addActionListener(evt -> jButtonPlayMoveActionPerformed(evt));

        jButton2.setText("Apply");
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPushToGoal)
                            .addComponent(jTextFieldMove)
                            .addComponent(jTextFieldPush, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonBrowsePush, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBrowseMove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBrowsePushToGoal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPlayPush)
                            .addComponent(jButtonPlayMove)
                            .addComponent(jButtonPlayPushToGoal))))
                .addGap(21, 21, 21))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonBrowseMove, jButtonBrowsePush, jButtonBrowsePushToGoal});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextFieldPush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPushToGoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBrowsePush)
                            .addComponent(jButtonPlayPush))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBrowseMove)
                            .addComponent(jButtonPlayMove))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBrowsePushToGoal)
                            .addComponent(jButtonPlayPushToGoal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonBrowsePush, jButtonPlayPush, jLabel2, jTextFieldPush});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonBrowseMove, jButtonPlayMove, jLabel3, jTextFieldMove});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonBrowsePushToGoal, jButtonPlayPushToGoal, jLabel4, jTextFieldPushToGoal});

        jCheckBoxSound.setText(Texts.getText("sound"));

        JLabel label = new JLabel("%");

        // Set at desired positions
        Hashtable<Integer, JLabel> labels = new Hashtable<Integer, JLabel>(5);
        for (int k=0; k<5; k++){
            labels.put(new Integer(25*k), new JLabel(25 * k +" %", JLabel.CENTER ));
        }
        // Force the slider to use the new labels
        jSlider1.setLabelTable(labels);
        jSlider1.setPaintTicks(true);
        jSlider1.setMajorTickSpacing(25);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintLabels( true );
        jSlider1.setBorder(javax.swing.BorderFactory.createTitledBorder("Volume"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxSound)
                        .addGap(18, 18, 18)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxSound)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(174, 174, 174)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCheckBoxSound, jSlider1});

        jCheckBoxSound.setActionCommand("sound");
        jCheckBoxSound.addActionListener(applicationGUI);

        jTabbedPane1.addTab("Sounds", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Look And Feel Selection"));

        UpdateSettingsFrame();
        jComboBoxLookAndFeelSelection.addActionListener(evt -> jComboBoxLookAndFeelSelectionActionPerformed(evt));

        jLabel5.setText("Look And Feel");

        jButtonApplyLookAndFeel.setText("Apply");
        jButtonApplyLookAndFeel.addActionListener(evt -> jButtonApplyLookAndFeelActionPerformed(evt));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addComponent(jComboBoxLookAndFeelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonApplyLookAndFeel)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxLookAndFeelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonApplyLookAndFeel)))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Changing Colors"));

        panelColorDisplayMovesPushes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelColorDisplayMovesPushes.setBackground(applicationGUI.mainBoardDisplay.colorDisplayMovesPushes);

        javax.swing.GroupLayout panelColorDisplayMovesPushesLayout = new javax.swing.GroupLayout(panelColorDisplayMovesPushes);
        panelColorDisplayMovesPushes.setLayout(panelColorDisplayMovesPushesLayout);
        panelColorDisplayMovesPushesLayout.setHorizontalGroup(
            panelColorDisplayMovesPushesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        panelColorDisplayMovesPushesLayout.setVerticalGroup(
            panelColorDisplayMovesPushesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jButtonColorDisplayMovesPushes.setText("Pick");
        jButtonColorDisplayMovesPushes.addActionListener(evt -> jButtonColorDisplayMovesPushesActionPerformed(evt));

        jLabelColorDisplayMovesPushes.setText("colorDisplayMovesPushes");

        jLabelColorBackgroundMovesPushes.setText("colorBackgroundMovesPushes");

        panelColorBackgroundMovesPushes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelColorBackgroundMovesPushes.setBackground(applicationGUI.mainBoardDisplay.colorBackgroundMovesPushes);

        javax.swing.GroupLayout panelColorBackgroundMovesPushesLayout = new javax.swing.GroupLayout(panelColorBackgroundMovesPushes);
        panelColorBackgroundMovesPushes.setLayout(panelColorBackgroundMovesPushesLayout);
        panelColorBackgroundMovesPushesLayout.setHorizontalGroup(
            panelColorBackgroundMovesPushesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        panelColorBackgroundMovesPushesLayout.setVerticalGroup(
            panelColorBackgroundMovesPushesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jButtonColorBackgroundMovesPushes.setText("Pick");
        jButtonColorBackgroundMovesPushes.addActionListener(evt -> jButtonColorBackgroundMovesPushesActionPerformed(evt));

        jLabelColorInfobar.setText("colorInfobar");

        panelColorInfobar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelColorInfobar.setBackground(applicationGUI.mainBoardDisplay.colorInfobar);

        javax.swing.GroupLayout panelColorInfobarLayout = new javax.swing.GroupLayout(panelColorInfobar);
        panelColorInfobar.setLayout(panelColorInfobarLayout);
        panelColorInfobarLayout.setHorizontalGroup(
            panelColorInfobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        panelColorInfobarLayout.setVerticalGroup(
            panelColorInfobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jButtonColorInfobar.setText("Pick");
        jButtonColorInfobar.addActionListener(evt -> jButtonColorInfobarActionPerformed(evt));

        jLabelColorInfobarFrame.setText("colorInfobarFrame");

        panelColorInfobarFrame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelColorInfobarFrame.setBackground(applicationGUI.mainBoardDisplay.colorInfobarFrame);

        javax.swing.GroupLayout panelColorInfobarFrameLayout = new javax.swing.GroupLayout(panelColorInfobarFrame);
        panelColorInfobarFrame.setLayout(panelColorInfobarFrameLayout);
        panelColorInfobarFrameLayout.setHorizontalGroup(
            panelColorInfobarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        panelColorInfobarFrameLayout.setVerticalGroup(
            panelColorInfobarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jButtonColorInfobarFrame.setText("Pick");
        jButtonColorInfobarFrame.addActionListener(evt -> jButtonColorInfobarFrameActionPerformed(evt));

        jLabelColorInfobarText.setText("colorInfobarText");

        panelColorInfobarText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelColorInfobarText.setBackground(applicationGUI.mainBoardDisplay.colorInfobarText);

        javax.swing.GroupLayout panelColorInfobarTextLayout = new javax.swing.GroupLayout(panelColorInfobarText);
        panelColorInfobarText.setLayout(panelColorInfobarTextLayout);
        panelColorInfobarTextLayout.setHorizontalGroup(
            panelColorInfobarTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        panelColorInfobarTextLayout.setVerticalGroup(
            panelColorInfobarTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jButtonColorInfobarText.setText("Pick");
        jButtonColorInfobarText.addActionListener(evt -> jButtonColorInfobarTextActionPerformed(evt));

        jLabelColorSelectedObjectFrame.setText("colorSelectedObjectFrame");

        panelColorSelectedObjectFrame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelColorSelectedObjectFrame.setBackground(applicationGUI.mainBoardDisplay.colorSelectedObjectFrame);

        javax.swing.GroupLayout panelColorSelectedObjectFrameLayout = new javax.swing.GroupLayout(panelColorSelectedObjectFrame);
        panelColorSelectedObjectFrame.setLayout(panelColorSelectedObjectFrameLayout);
        panelColorSelectedObjectFrameLayout.setHorizontalGroup(
            panelColorSelectedObjectFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        panelColorSelectedObjectFrameLayout.setVerticalGroup(
            panelColorSelectedObjectFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jButtonColorSelectedObjectFrame.setText("Pick");
        jButtonColorSelectedObjectFrame.addActionListener(evt -> jButtonColorSelectedObjectFrameActionPerformed(evt));

        jLabelColorNumberOfBoxesGoals.setText("colorNumberOfBoxesGoals");

        panelColorNumberOfBoxesGoals.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelColorNumberOfBoxesGoals.setBackground(applicationGUI.mainBoardDisplay.colorNumberOfBoxesGoals);

        javax.swing.GroupLayout panelColorNumberOfBoxesGoalsLayout = new javax.swing.GroupLayout(panelColorNumberOfBoxesGoals);
        panelColorNumberOfBoxesGoals.setLayout(panelColorNumberOfBoxesGoalsLayout);
        panelColorNumberOfBoxesGoalsLayout.setHorizontalGroup(
            panelColorNumberOfBoxesGoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        panelColorNumberOfBoxesGoalsLayout.setVerticalGroup(
            panelColorNumberOfBoxesGoalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jButtonColorNumberOfBoxesGoals.setText("Pick");
        jButtonColorNumberOfBoxesGoals.addActionListener(evt -> jButtonColorNumberOfBoxesGoalsActionPerformed(evt));

        jLabelColorSelectedBoxFrame.setText("colorSelectedBoxFrame");

        panelColorSelectedBoxFrame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelColorSelectedBoxFrame.setBackground(applicationGUI.mainBoardDisplay.colorSelectedBoxFrame);

        javax.swing.GroupLayout panelColorSelectedBoxFrameLayout = new javax.swing.GroupLayout(panelColorSelectedBoxFrame);
        panelColorSelectedBoxFrame.setLayout(panelColorSelectedBoxFrameLayout);
        panelColorSelectedBoxFrameLayout.setHorizontalGroup(
            panelColorSelectedBoxFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        panelColorSelectedBoxFrameLayout.setVerticalGroup(
            panelColorSelectedBoxFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jButtonColorSelectedBoxFrame.setText("Pick");
        jButtonColorSelectedBoxFrame.addActionListener(evt -> jButtonColorSelectedBoxFrameActionPerformed(evt));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabelColorDisplayMovesPushes, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabelColorBackgroundMovesPushes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabelColorInfobar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabelColorInfobarFrame)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabelColorSelectedObjectFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelColorDisplayMovesPushes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelColorBackgroundMovesPushes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelColorInfobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelColorInfobarFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelColorInfobarText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelColorSelectedObjectFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelColorNumberOfBoxesGoals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelColorSelectedBoxFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelColorNumberOfBoxesGoals, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelColorSelectedBoxFrame)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelColorInfobarText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonColorSelectedBoxFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorNumberOfBoxesGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorSelectedObjectFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorInfobarText, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jButtonColorInfobarFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jButtonColorInfobar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorBackgroundMovesPushes, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jButtonColorDisplayMovesPushes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelColorBackgroundMovesPushes, jLabelColorDisplayMovesPushes, jLabelColorInfobar, jLabelColorInfobarFrame, jLabelColorInfobarText, jLabelColorNumberOfBoxesGoals, jLabelColorSelectedBoxFrame, jLabelColorSelectedObjectFrame});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {panelColorBackgroundMovesPushes, panelColorDisplayMovesPushes, panelColorInfobar, panelColorInfobarFrame, panelColorInfobarText, panelColorNumberOfBoxesGoals, panelColorSelectedBoxFrame, panelColorSelectedObjectFrame});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonColorBackgroundMovesPushes, jButtonColorDisplayMovesPushes, jButtonColorInfobar, jButtonColorInfobarFrame, jButtonColorInfobarText, jButtonColorNumberOfBoxesGoals, jButtonColorSelectedBoxFrame, jButtonColorSelectedObjectFrame});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonColorDisplayMovesPushes, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(panelColorDisplayMovesPushes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelColorDisplayMovesPushes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelColorBackgroundMovesPushes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelColorBackgroundMovesPushes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorBackgroundMovesPushes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelColorInfobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelColorInfobar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColorInfobar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelColorInfobarFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelColorInfobarFrame, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonColorInfobarFrame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelColorInfobarText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelColorInfobarText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonColorInfobarText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelColorSelectedObjectFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelColorSelectedObjectFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelColorNumberOfBoxesGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelColorNumberOfBoxesGoals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButtonColorSelectedObjectFrame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonColorNumberOfBoxesGoals)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelColorSelectedBoxFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelColorSelectedBoxFrame))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButtonColorSelectedBoxFrame)
                        .addContainerGap())))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonColorBackgroundMovesPushes, jLabelColorBackgroundMovesPushes, panelColorBackgroundMovesPushes});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonColorInfobar, jLabelColorInfobar, panelColorInfobar});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonColorInfobarFrame, jLabelColorInfobarFrame, panelColorInfobarFrame});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonColorInfobarText, jLabelColorInfobarText, panelColorInfobarText});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonColorSelectedObjectFrame, jLabelColorSelectedObjectFrame, panelColorSelectedObjectFrame});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonColorNumberOfBoxesGoals, panelColorNumberOfBoxesGoals});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonColorSelectedBoxFrame, jLabelColorSelectedBoxFrame, panelColorSelectedBoxFrame});

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("NimROD L&F"));

        jButtonNimRODLF.setText("NimROD L&F");
        jButtonNimRODLF.setActionCommand("nimRODLookAndFeel");
        jButtonNimRODLF.addActionListener(applicationGUI);

        jButtonLoadThemeNimRODLF.setText(Texts.getText("menu.nimROD.loadThemeNimRODL&F"));
        jButtonLoadThemeNimRODLF.setActionCommand("loadThemeNimRODL&F");
        jButtonLoadThemeNimRODLF.addActionListener(applicationGUI);

        jButtonCustomizeNimRODLF.setText(Texts.getText("menu.nimROD.customizeNimRODL&F"));
        jButtonCustomizeNimRODLF.setActionCommand("customizeNimRODL&F");
        jButtonCustomizeNimRODLF.addActionListener(applicationGUI);

        jButtonSetDefaultThemeNimRODLF.setText(Texts.getText("menu.nimROD.setDefaultTheme"));
        jButtonSetDefaultThemeNimRODLF.setActionCommand("setDefaultThemeNimRODL&F");
        jButtonSetDefaultThemeNimRODLF.addActionListener(applicationGUI);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNimRODLF)
                    .addComponent(jButtonLoadThemeNimRODLF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCustomizeNimRODLF)
                    .addComponent(jButtonSetDefaultThemeNimRODLF))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCustomizeNimRODLF, jButtonSetDefaultThemeNimRODLF});

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonLoadThemeNimRODLF, jButtonNimRODLF});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNimRODLF)
                    .addComponent(jButtonCustomizeNimRODLF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoadThemeNimRODLF)
                    .addComponent(jButtonSetDefaultThemeNimRODLF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(77, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(360, 360, 360))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(360, 360, 360))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel10, jPanel7, jPanel9});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Appearance", jPanel3);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Font Selection"));

        bold.setText("Bold");

        italic.setText("Italic");

        fontList = GraphicsEnvironment.getLocalGraphicsEnvironment()
        .getAvailableFontFamilyNames();

        for (String s : fontList) {
            fontNameChoice.add(s);
        }
        fontNameChoice.select(0);

        for (String fontSize : fontSizes) {
            fontSizeChoice.add(fontSize);
        }
        fontSizeChoice.select(DEFAULT_SIZE);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontNameChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontSizeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bold)
                    .addComponent(italic))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bold, italic});

        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fontNameChoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(bold)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(italic))
                    .addComponent(fontSizeChoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fontNameChoice, fontSizeChoice});

        okButton.setText("Apply");

        jButton5.setText("Preview");
        jButton5.addActionListener(evt -> jButton5ActionPerformed(evt));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(resultFont))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(308, 308, 308))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultFont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton)
                    .addComponent(jButton5))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton5, okButton});

        jTabbedPane1.addTab("Font Selection", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        previewFont();
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonColorSelectedBoxFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorSelectedBoxFrameActionPerformed
        Color acolor = pickColor(panelColorSelectedBoxFrame.getBackground());
        panelColorSelectedBoxFrame.setBackground(acolor);
        Settings.set("colorSelectedBoxFrame", acolor.getRed() + "," + acolor.getGreen() + "," + acolor.getBlue());
        applicationGUI.mainBoardDisplay.colorSelectedBoxFrame = acolor;
        applicationGUI.mainBoardDisplay.repaint();
}//GEN-LAST:event_jButtonColorSelectedBoxFrameActionPerformed

    private void jButtonColorNumberOfBoxesGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorNumberOfBoxesGoalsActionPerformed
        Color acolor = pickColor(panelColorNumberOfBoxesGoals.getBackground());
        panelColorNumberOfBoxesGoals.setBackground(acolor);
        Settings.set("colorNumberOfBoxesGoals", acolor.getRed() + "," + acolor.getGreen() + "," + acolor.getBlue());
        applicationGUI.mainBoardDisplay.colorNumberOfBoxesGoals = acolor;
        applicationGUI.mainBoardDisplay.repaint();
}//GEN-LAST:event_jButtonColorNumberOfBoxesGoalsActionPerformed

    private void jButtonColorSelectedObjectFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorSelectedObjectFrameActionPerformed
        Color acolor = pickColor(panelColorSelectedObjectFrame.getBackground());
        panelColorSelectedObjectFrame.setBackground(acolor);
        Settings.set("colorSelectedObjectFrame", acolor.getRed() + "," + acolor.getGreen() + "," + acolor.getBlue());
        applicationGUI.mainBoardDisplay.colorSelectedObjectFrame = acolor;
        applicationGUI.mainBoardDisplay.repaint();
}//GEN-LAST:event_jButtonColorSelectedObjectFrameActionPerformed

    private void jButtonColorInfobarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorInfobarTextActionPerformed

        Color acolor = pickColor(panelColorInfobarText.getBackground());
        panelColorInfobarText.setBackground(acolor);
        Settings.set("colorInfobarText", acolor.getRed() + "," + acolor.getGreen() + "," + acolor.getBlue());
        applicationGUI.mainBoardDisplay.colorInfobarText = acolor;
        applicationGUI.mainBoardDisplay.repaint();
}//GEN-LAST:event_jButtonColorInfobarTextActionPerformed

    private void jButtonColorInfobarFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorInfobarFrameActionPerformed
        //Color acolor = pickColor();
        Color acolor = null;
        panelColorInfobarFrame.setBackground(acolor);
        applicationGUI.mainBoardDisplay.colorInfobarFrame = acolor;
        applicationGUI.mainBoardDisplay.repaint();
}//GEN-LAST:event_jButtonColorInfobarFrameActionPerformed

    private void jButtonColorInfobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorInfobarActionPerformed
        //Color acolor = pickColor();
        Color acolor = null;
        panelColorInfobar.setBackground(acolor);
        applicationGUI.mainBoardDisplay.colorInfobar = acolor;
        applicationGUI.mainBoardDisplay.repaint();
}//GEN-LAST:event_jButtonColorInfobarActionPerformed

    private void jButtonColorBackgroundMovesPushesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorBackgroundMovesPushesActionPerformed
        // TODO add your handling code here:
        Color acolor = pickColor(panelColorBackgroundMovesPushes.getBackground());

        panelColorBackgroundMovesPushes.setBackground(acolor);
        Settings.set("colorBackgroundMovesPushes", acolor.getRed() + "," + acolor.getGreen() + "," + acolor.getBlue() + "," + acolor.getAlpha());
        applicationGUI.mainBoardDisplay.colorBackgroundMovesPushes = acolor;
        applicationGUI.mainBoardDisplay.repaint();
}//GEN-LAST:event_jButtonColorBackgroundMovesPushesActionPerformed

    private void jButtonColorDisplayMovesPushesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorDisplayMovesPushesActionPerformed
        // TODO add your handling code here:

        Color acolor = pickColor(panelColorDisplayMovesPushes.getBackground());
        panelColorDisplayMovesPushes.setBackground(acolor);
        Settings.set("colorDisplayMovesPushes", acolor.getRed() + "," + acolor.getGreen() + "," + acolor.getBlue());
        applicationGUI.mainBoardDisplay.colorDisplayMovesPushes = acolor;
        applicationGUI.mainBoardDisplay.repaint();
}//GEN-LAST:event_jButtonColorDisplayMovesPushesActionPerformed

    private void jButtonApplyLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyLookAndFeelActionPerformed
        // TODO add your handling code here:
        LookAndFeelInfo[] info = UIManager.getInstalledLookAndFeels();
        for (LookAndFeelInfo lfInfo : info) {
            if (lfInfo.getName().equals(lookAndFeelName)) {
                System.out.println(lfInfo.getClassName());
                try {
                    UIManager.setLookAndFeel(lfInfo.getClassName());
                    Utilities.updateUI(); // update all swing windows
                    Settings.currentLookAndFeel = lfInfo.getClassName(); // save it to settings file
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SettingsFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(SettingsFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(SettingsFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(SettingsFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
}//GEN-LAST:event_jButtonApplyLookAndFeelActionPerformed

    private void jComboBoxLookAndFeelSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLookAndFeelSelectionActionPerformed
        // TODO add your handling code here:
        lookAndFeelName = (String) jComboBoxLookAndFeelSelection.getSelectedItem();
}//GEN-LAST:event_jComboBoxLookAndFeelSelectionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Settings.set("MoveSoundFile", jTextFieldMove.getText());
        Settings.set("PushSoundFile", jTextFieldPush.getText());
        Settings.set("PushToGoalSoundFile", jTextFieldPushToGoal.getText());
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonPlayMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayMoveActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonPlayMoveActionPerformed

    private void jButtonPlayPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayPushActionPerformed
        // TODO add your handling code here:
        //Sound.playSound(Sound.PUSH);
}//GEN-LAST:event_jButtonPlayPushActionPerformed

    private void jButtonBrowsePushToGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowsePushToGoalActionPerformed
        // TODO add your handling code here:
        File pushtoGoal = browseFile();
        jTextFieldPushToGoal.setText(pushtoGoal.getAbsolutePath());
}//GEN-LAST:event_jButtonBrowsePushToGoalActionPerformed

    private void jButtonBrowseMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseMoveActionPerformed
        // TODO add your handling code here:
        File move = browseFile();
        jTextFieldMove.setText(move.getAbsolutePath());
}//GEN-LAST:event_jButtonBrowseMoveActionPerformed

    private void jButtonBrowsePushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowsePushActionPerformed
        // TODO add your handling code here:
        File push = browseFile();
        jTextFieldPush.setText(push.getAbsolutePath());
}//GEN-LAST:event_jButtonBrowsePushActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        System.out.println(languageName);
        System.out.println(Translator.getLanguageCode(languageName));
//        setLanguage(Translator.getLanguageCode(languageName));

        // Let the GUI set the language in all components.
        applicationGUI.setNewLanguage();

        // Optimizer, solutions view,... aren't updated. Hence, a message for the user is displayed.
        JOptionPane.showMessageDialog(this, Texts.getText("languageChange"), Texts.getText("note"), JOptionPane.OK_OPTION);

        UpdateSettingsFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxLanguagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLanguagesActionPerformed
        // TODO add your handling code here:
        languageName = (String) comboBoxLanguages.getSelectedItem();
        applicationGUI.mainBoardDisplay.repaint();
}//GEN-LAST:event_comboBoxLanguagesActionPerformed

    private void UpdateSettingsFrame() {

        //languages combo box
        int noLanguages = 0;
        for (String l : Translator.getAvailableLanguageNames()) {
            noLanguages++;
        }
        String[] ArrayLanguages = new String[noLanguages];
        int i = 0;
        for (String l : Translator.getAvailableLanguageNames()) {
            ArrayLanguages[i] = l;
            i++;
        }
        comboBoxLanguages.setModel(new javax.swing.DefaultComboBoxModel(ArrayLanguages));

        //look and feel combo box
        int noLookAndFeel = 0;
        LookAndFeelInfo[] info = UIManager.getInstalledLookAndFeels();

        for (LookAndFeelInfo lfInfo : info) {
            noLookAndFeel++;
        }
        String[] ArrayLookAndFeel = new String[noLookAndFeel];
        noLookAndFeel = 0;
        for (LookAndFeelInfo lfInfo : info) {
            ArrayLookAndFeel[noLookAndFeel] = lfInfo.getName();
            noLookAndFeel++;
        }
        jComboBoxLookAndFeelSelection.setModel(new javax.swing.DefaultComboBoxModel(ArrayLookAndFeel));

        // update checkboxes
        jCheckBoxDetectSimpleDeadlocks.setText(Texts.getText("detectSimpleDeadlocks"));
        jCheckBoxDetectBipartiteDeadlocks.setText(Texts.getText("detectBipartiteDeadlocks"));
        jCheckBoxDetectCorralDeadlocks.setText(Texts.getText("detectCorralDeadlocks"));
        jCheckBoxDetectFreezeDeadlocks.setText(Texts.getText("detectFreezeDeadlocks"));
        jCheckBoxSinglestepundo.setText(Texts.getText("singlestepundo"));
        jCheckBoxReverseMoves.setText(Texts.getText("treat_reverse_moves_as_undo"));
        jCheckBoxSound.setText(Texts.getText("sound"));
        jCheckBoxOptimize_moves.setText(Texts.getText("optimize_moves"));
    }

    protected File browseFile() {
        JFileChooser push = new JFileChooser();
        int returnValue = push.showOpenDialog(null);
        push.setVisible(true);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = push.getSelectedFile();
            System.out.println(selectedFile);
            return selectedFile;
        } else {
            return null;
        }

    }

    protected Color pickColor(Color before) {

        Color after = JColorChooser.showDialog(rootPane, "Choose a Color", before);
        if (after == null) {
            return before;
        }
        return after;
    }

    private void previewFont() {
        resultName = fontNameChoice.getSelectedItem();
        String resultSizeName = fontSizeChoice.getSelectedItem();
        int resultSize = Integer.parseInt(resultSizeName);

        int attrs = Font.PLAIN;
        if (bold.isSelected()) {
            attrs = Font.BOLD;
        }
        if (italic.isSelected()) {
            attrs |= Font.ITALIC;
        }

        resultFont.setFont(new Font(resultName, attrs, resultSize));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new SettingsFrame().setVisible(true));
    }
    private String lookAndFeelName;
    private String languageName;
    private GUI applicationGUI;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bold;
    private javax.swing.JComboBox comboBoxLanguages;
    private java.awt.List fontNameChoice;
    private java.awt.List fontSizeChoice;
    private javax.swing.JCheckBox italic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonApplyLookAndFeel;
    private javax.swing.JButton jButtonBrowseMove;
    private javax.swing.JButton jButtonBrowsePush;
    private javax.swing.JButton jButtonBrowsePushToGoal;
    private javax.swing.JButton jButtonColorBackgroundMovesPushes;
    private javax.swing.JButton jButtonColorDisplayMovesPushes;
    private javax.swing.JButton jButtonColorInfobar;
    private javax.swing.JButton jButtonColorInfobarFrame;
    private javax.swing.JButton jButtonColorInfobarText;
    private javax.swing.JButton jButtonColorNumberOfBoxesGoals;
    private javax.swing.JButton jButtonColorSelectedBoxFrame;
    private javax.swing.JButton jButtonColorSelectedObjectFrame;
    private javax.swing.JButton jButtonCustomizeNimRODLF;
    private javax.swing.JButton jButtonLoadThemeNimRODLF;
    private javax.swing.JButton jButtonNimRODLF;
    private javax.swing.JButton jButtonPlayMove;
    private javax.swing.JButton jButtonPlayPush;
    private javax.swing.JButton jButtonPlayPushToGoal;
    private javax.swing.JButton jButtonSetDefaultThemeNimRODLF;
    private javax.swing.JButton jButtonTranslate;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JCheckBox jCheckBoxDetectBipartiteDeadlocks;
    private javax.swing.JCheckBox jCheckBoxDetectCorralDeadlocks;
    private javax.swing.JCheckBox jCheckBoxDetectFreezeDeadlocks;
    private javax.swing.JCheckBox jCheckBoxDetectSimpleDeadlocks;
    private javax.swing.JCheckBox jCheckBoxOptimize_moves;
    private javax.swing.JCheckBox jCheckBoxReverseMoves;
    private javax.swing.JCheckBox jCheckBoxSinglestepundo;
    private javax.swing.JCheckBox jCheckBoxSound;
    private javax.swing.JComboBox jComboBoxLookAndFeelSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelColorBackgroundMovesPushes;
    private javax.swing.JLabel jLabelColorDisplayMovesPushes;
    private javax.swing.JLabel jLabelColorInfobar;
    private javax.swing.JLabel jLabelColorInfobarFrame;
    private javax.swing.JLabel jLabelColorInfobarText;
    private javax.swing.JLabel jLabelColorNumberOfBoxesGoals;
    private javax.swing.JLabel jLabelColorSelectedBoxFrame;
    private javax.swing.JLabel jLabelColorSelectedObjectFrame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldMove;
    private javax.swing.JTextField jTextFieldPush;
    private javax.swing.JTextField jTextFieldPushToGoal;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel panelColorBackgroundMovesPushes;
    private javax.swing.JPanel panelColorDisplayMovesPushes;
    private javax.swing.JPanel panelColorInfobar;
    private javax.swing.JPanel panelColorInfobarFrame;
    private javax.swing.JPanel panelColorInfobarText;
    private javax.swing.JPanel panelColorNumberOfBoxesGoals;
    private javax.swing.JPanel panelColorSelectedBoxFrame;
    private javax.swing.JPanel panelColorSelectedObjectFrame;
    private javax.swing.JLabel resultFont;
    // End of variables declaration//GEN-END:variables
}
